apiVersion: v1
kind: Service
metadata:
  name: pdf-audiobook-service
spec:
  selector:
    app: pdf-audiobook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30001
  type: NodePort